pagopa/selfcare-dashboard-users-microfrontend

src/pages/dashboardUserEdit/AddProductToUserPage.tsx

added backcomponent in breadcrumb of assign new role page

---

openApi/dashboard-api-docs.json
src/api/DashboardApiClient.ts
src/api/__mocks__/DashboardApiClient.ts
src/model/PartyUser.ts
src/model/UserRegistry.ts
src/pages/dashboardUserEdit/components/EditUserRegistryForm.tsx
src/services/__mocks__/usersService.ts

* SELC-1412 - updated with openApi
* SELC-1412 - updated with last openApi
Co-authored-by: fp <federico.piacitelli@everis.com>

SELC-1412 - updated with openApi

---

openApi/dashboard-api-docs.json

updated openApi

---

src/pages/dashboardUserDetail/components/UserDetail.tsx
src/pages/dashboardUserDetail/userDetailPage/components/UserProductDetail.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UserProductRowActions.tsx

SELC-1476 - added placement and arrow in Tooltip

SELC-1476 - added placement and arrow in Tooltip

---

package.json
yarn.lock

Update mui-italia dependence at the most recent version

---

src/pages/dashboardUsers/components/UsersTableProduct/UsersTableProduct.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

Fixed persistant load more bug

---

package.json
yarn.lock

SELC-1509_addedNewCase Added new case to cover one consonant names

---

package.json
src/pages/dashboardUserEdit/EditUserRegistryPage.tsx
yarn.lock

* SELC-1509_addedNewCase Added new case to cover one consonant names
* SELC-1509_addedNewCases Added other particularly but probably cases in order to cover all request

SELC-1509 added other particularly but probably cases in order to cover all possibilities

---

src/pages/dashboardUserDetail/components/AddUserToGroupButton.tsx
src/pages/dashboardUserDetail/components/UserProductGroups.tsx
src/pages/dashboardUserEdit/__tests__/EditUserRegistryPage.test.tsx
src/pages/dashboardUserEdit/components/EditUserRegistryForm.tsx

* SELC-1519 Resolved bug on "second try" redirect when user press back button in editRegistryForm
* SELC-1519 Fixed unitTest

SELC-1519 Modifica Utente - al click tasto Indietro (in basso) non abbandono la pagina

---

package.json
yarn.lock

SELC-1589 Managment of aphostrophe, in order to not consider it as a consonant in taxCode match

---

package.json
yarn.lock

SELC-1589 Management of multiple apostrophes too

---

src/pages/dashboardUsers/__tests__/UsersPage.test.tsx
src/pages/dashboardUsers/components/UsersTableActions/UsersTableRolesFilter.tsx

* SELC-1007 AllRoles select is now accessible + optimization in code
* SELC-1007 fixed UnitTest
* temp commit
* SELC-1007 Fix broken unitTest
* Removed refuse

SELC-1007 AllRoles select is now accessible + optimization in code

---

src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx

* Selected product in addUserForm when there are environments product on PNPG
* fixed little typo

Select product in addUserForm when there are environments product on PNPG

---

src/pages/dashboardUserDetail/userDetailPage/components/UserProductSection.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx
src/pages/dashboardUsers/UsersPage/UsersPage.tsx
src/pages/dashboardUsers/components/UsersProductSection.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UserProductTableColumns.tsx

* Fixed graphic bugs after adding environment PNPG products feature
* Show the label user data if there is pnpg among the products

Fixed graphics bug when are present multi pnpg environents product

---

src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx
src/pages/dashboardUsers/UsersPage/UsersPage.tsx
src/pages/dashboardUsers/components/MobileFilter.tsx

- AddUserForm in the mobile version extends in width and is fully responsive.
- Moved the new mobile dialog in a own component.

PNPG-156 AddUserForm in the mobile version extends in width and is fully responsive + Moved the new mobile dialog in a own component

---

package.json
yarn.lock

Updated common dependency at the most recent version for responsive modals

PNPG-196 Updated common dependency at the most recent version for responsive modals

---

package.json
src/pages/dashboardUserEdit/components/AddUserForm.tsx
yarn.lock

Set the prop size to medium in the buttons present in the add user form
Release in UAT of task PNPG-199, that set prop size of buttons on add user form to medium to prevent them from expanding to full width when browser size changes
By shrinking the browser window, the buttons will remain with the same width

PNPG-199 PNPG-200

---

package.json
yarn.lock

merge back from main
merge back from main after direct fix in prod

Merge back from main

---

src/pages/dashboardUserDetail/components/UserDetail.tsx

added margin in user detail info

SELC-2663 - added margin in user detail info

---

src/pages/dashboardUserDetail/components/UserDetail.tsx

added margin in user detail info

SELC-2659 - added margin in user detail info

---

package.json
yarn.lock

Updating of the mui-italia library version in order to obtain the new changes to the ProductAvatar component

---

package.json
src/locale/de.ts
src/locale/en.ts
src/locale/fr.ts
src/locale/index.ts
src/locale/locale-utils.ts
src/locale/sl.ts
src/pages/dashboardUsers/UsersPage/UsersPage.tsx
yarn.lock

Release in UAT environment of Added localization languages: english, german, french, slovenian

SELC-2582 Added localization languages: english, german, french, slovenian

---

src/pages/dashboardUserEdit/components/AddUserForm.tsx
src/pages/dashboardUserEdit/components/EditUserRegistryForm.tsx

More flexible regexp in order to accept 5 characters after dot

More flexible regexp in order to accept 5 characters after dot

---

src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx

Party admin can modify the user's personal data
Party admin can modify the user's personal data not party user

SELC-2986 Party admin can modify the user's personal data

---

src/pages/dashboardUserDetail/components/UserDetail.tsx

Release in dev environment of Setted email of user detail as optional for manage potentially undefined on pnpg
On PNPG, we can have some case when the email arrive undefined because that data is not persisted on DB after onboarding. For manage it, we set as optional

Setted email of user detail as optional for manage potentially undefined on pnpg

---

src/pages/dashboardUserDetail/userDetailPage/components/UserProductSection.tsx

Assign role button will appear only if are present available roles
The assign role button appeared even when there were no available roles, now it only appears when there are available roles
Assign role button will appear only if are present available roles
Tested using DEV environment data

Assign role button will appear only if are present available roles

---

package.json
src/pages/dashboardUserDetail/userDetailPage/components/UserProductSection.tsx
yarn.lock

- SELC-3090 Added "accessibility" voice in the footer (for logged and not logged in)
Release in prod environment of the feature worked
By testing locally and aiming environments from dev team and with behaviour test from QA team

Release prod

---

.devops/deploy-pipelines.yml
package.json
src/pages/dashboardUserEdit/components/AddUserForm.tsx
src/pages/dashboardUserEdit/components/EditUserRegistryForm.tsx
yarn.lock

SELC-3127 Updated @pagopa/selfcare-common-frontend to 1.34.8
update to 1.34.9
add env variables in pipeline deploy for privacy and terms
add import for emailRegex from common
Need to update for keep the versions the same with dashboard FE

Updated selfcare-common-frontend to 1.34.9 and added env vars

---

package.json
src/microcomponents/mock_dashboard/Layout.tsx
src/utils/env.ts
yarn.lock

SELC-3135 add documentation button in header
update common library
Tested locally

SELC-3135 update common and add documentation button in header

---

package.json
src/locale/de.ts
src/locale/en.ts
src/locale/fr.ts
src/locale/sl.ts
yarn.lock

SELC-3242 Updated translation json files
updated common library

SELC-3242 Updated translation json files

---

package.json
src/locale/de.ts
src/locale/en.ts
src/locale/fr.ts
src/locale/sl.ts
yarn.lock

* SELC-3242 updated translation json files
* updated common library
To keep the translation files and common library updated

SELC-3242 Updated translation json files and updated common

---

src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

Transform user names to lower case before sorting.

[SELC-2398] fix: case insensitive sorting for users

---

src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

Update if condition of name of variable

[SELC-2398] fix: update if condition variable name

---

src/pages/dashboardUsers/components/UsersTableProduct/components/UserProductTableColumns.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

Sorting of users by surname first  
Format of users name with first letter capitalized.
Often we dont have the user name only the surname so its easer to find the user by surname.
Tested in dev

[SELC-3616] feat: sort user list by surname and format the names.

---

src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

The current logged in user will alwas appear in first place regardless of sorting.

[SELC-939] feat: Put the current logged in first place of the list in the users page

---

.env.development.local
openApi/dashboard-api-docs.json

update dashboard swagger with new paths with versioning
In order to remove versioning from env variable and add it in the path.

[SELC-4341] Feat: update swagger with versioning in path

---

src/microcomponents/mock_dashboard/Layout.tsx

hide documentation button
The documentation of selfcare at the moment is only in italian so it should not be avaible to other languages

[SELC-4492] Feat: hide documentation button

---

openApi/dashboard-api-docs.json
src/api/DashboardApiClient.ts
src/services/usersService.ts

Added new v2 PUT api to update user data 
Removed old api call with new one after user ms refactor.
Tested locally by aiming at dev data

[SELC-4499] Feat: Add update user v2 api call

---

openApi/dashboard-api-docs.json
src/api/DashboardApiClient.ts
src/services/groupsService.ts
src/services/usersService.ts

Switched all user-groups api to version 2
To migrate from v1 to v2 users and groups
Tested locally and dev

[SELC-4538] Feat: Migrate to v2 for user-groups and update openApi

---

openApi/dashboard-api-docs.json
src/api/DashboardApiClient.ts
src/services/usersService.ts

Add new api
In order to witch v2 retrive user list
Tested local

[SELC-4496] Feat: Integrate new api to retrieve users list

---

src/api/DashboardApiClient.ts
src/services/usersService.ts

adde the product id as a filter 
To allow deploy in prod of FE

Fix: Add filter by product id users list api call

---

src/pages/dashboardUserDetail/__tests__/UserDetailPage.test.tsx
src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx

- Change location when pressing back in ProductNavigationBar component
- adapt unit tests
Fix for bug 
Tested locally and with dev enviroment data

[SELC-4841]  fix: pathing when using ProductNavigationBar in user detail page

---

src/pages/dashboardUserDetail/__tests__/UserDetailPage.test.tsx
src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx

[SELC-4841]  fix: pathing when using ProductNavigationBar in user detail page
adapt unit tests.
To fix bug
Tested in de enviroment
[SELC-4841]: https://pagopa.atlassian.net/browse/SELC-4841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-4841]  Release UAT

---

src/locale/it.ts
src/pages/dashboardUserEdit/components/AddUserForm.tsx

Add alert component in add users page when adding users to Interop prod
Add link to documentation
Its not possible in selfcare to add an admin to interop. Show a alert with a link to documentation on how to added it
Tested locally

[SELC-4815] Feat: add link to documentation for interop PROD

---

src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx

change the layout in user details page
To follow UI design
Tested in local

[SELC-4557] Feat: align elemnts in user detail page

---

src/locale/it.ts
src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx

[[SELC-4815] Feat: add link to documentation for interop PROD](https://github.com/pagopa/selfcare-dashboard-users-microfrontend/commit/46f3332aa3009ee05f8d4958fdf8764b0fda78e4)
[[SELC-4557] Feat: align elemnts in user detail page](https://github.com/pagopa/selfcare-dashboard-users-microfrontend/commit/535b9bae670b408b770aaf12a633151a8b6a3a21)
To release in uat enviroment worked feateures
Tested in dev
[SELC-4815]: https://pagopa.atlassian.net/browse/SELC-4815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-4557]: https://pagopa.atlassian.net/browse/SELC-4557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release Uat

---

src/pages/dashboardUsers/__tests__/UsersPage.test.tsx
src/pages/dashboardUsers/components/UsersTableProduct/UsersTableProduct.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx
src/remotes/__tests__/RoutingUsers.test.tsx
src/utils/utils.ts

fixed sorting 
adpat unit tests
Fixed so that the entire users list is ordered not only the first page
Tested locally

[SELC-4907] Fix: sort users on all pages

---

src/pages/dashboardUsers/UsersPage/UsersPage.tsx

Change background color
Tested locally

[SELC-4555] Feat: Adapt background colors of table to MUI design

---

src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

changed on hover color of table row 
To follow MUI style guidelines
Tested locally

[SELC-4554] Feat: change on hover of table row

---

package.json
yarn.lock

upate mui library version
To get the new color styles for chip and tag components

[SELC-4552] Feat: upate mui library version

---

src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

changed border radius of users when in mobile break point
To adapt the border radius of users row in datagrid
Tested locally

[SELC-4556] Feat: change border radius in mobile breakpoint

---

package.json
yarn.lock

update the mui italia library to get the new drawer

[SELC-4585] Feat: Update mui italia library

---

package.json
src/components/ProductNavigationBar.tsx
src/pages/dashboardUserDetail/__tests__/UserDetailPage.test.tsx
src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx
src/pages/dashboardUserEdit/AddProductToUserPage.tsx
src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/EditUserRegistryPage.tsx
src/pages/dashboardUserEdit/__tests__/EditUserRegistryPage.test.tsx
yarn.lock

update coomon library
update mui itlaia
change breadcrumb design
Tested locally

[SELC-4547] feat: Responsive breacrumb design

---

src/pages/dashboardUserDetail/components/UserDetail.tsx

changed how the responsive of the text in the user detail page
To adapt the page to mui design standard
Tested locally

[SELC-4558] Feat: change layout of use detail page

---

src/model/Party.tsx
src/model/PartyUser.ts
src/model/ProductRole.ts
src/pages/dashboardUsers/UsersPage/UsersPage.tsx
src/pages/dashboardUsers/components/UsersTableActions/UsersTableRolesFilter.tsx

enable horizontal scroll for tabs in users page
product name do not go on new line if the name is to long
To adapt the tabs component to mui design
Tested locally and by deploying branch in dev.

[SELC-4619] feat: Tabs in users page are scrallable horizontally

---

src/pages/dashboardUsers/UsersPage/UsersPage.tsx
src/pages/dashboardUsers/components/MobileFilter.tsx
src/pages/dashboardUsers/components/UsersTableActions/UsersTableRolesFilter.tsx

Modified MobileDialog component for better responsiveness in xs and sm breakpoints
Adjusted UsersTableActions layout to stack vertically on mobile
Added filter icon to "Add Filters" button for improved UX
These changes aim to enhance the user experience on mobile devices by improving the layout and functionality of the filter dialog. The addition of the filter icon provides better visual cues for users, while the responsive layout adjustments ensure consistent behavior across different screen sizes.
Tested on various mobile devices (iOS and Android) and browsers
Verified correct layout in both portrait and landscape orientations
Ensured filter functionality works as expected after UI changes

[SELC-4569] feat: Enhance mobile filter UI and improve responsive layout

---

openApi/dashboard-api-docs.json
package.json
src/api/DashboardApiClient.ts
src/api/__mocks__/DashboardApiClient.ts
src/decorators/withUserDetail.tsx
src/decorators/withUserRegistry.tsx
src/microcomponents/mock_dashboard/App.tsx
src/microcomponents/mock_dashboard/data/party.ts
src/model/Party.tsx
src/model/PartyUser.ts
src/model/Product.tsx
src/model/__tests__/PartyUser.test.ts
src/pages/dashboardUserDetail/components/UserProductGroups.tsx
src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx
src/pages/dashboardUserDetail/userDetailPage/components/UserProductSection.tsx
src/pages/dashboardUserEdit/__tests__/AddUsersPage.test.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx
src/pages/dashboardUsers/UsersPage/UsersPage.tsx
src/redux/store.ts
yarn.lock

Adapt pnpg dashboard to hadnle authorizations with the actions
updated the swagger
In order to have a better more scalable handling of the user roles and actions.
Tested in dev

[SELC-5262] feat: handle in pnpg dashboard to userProductActions

---

src/components/ProductNavigationBar.tsx
src/locale/it.ts
src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx
src/pages/dashboardUserEdit/AddProductToUserPage.tsx
src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/EditUserRegistryPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx

Updated users page following the figma design
hidded sidebar of add users page
In order to allow adding administrator on interperabiltà product updated the page layout.
Tested in local enviroment

[SELC-5367] Feat: updated add user page for administrators on interop

---

.devops/deploy-pipelines.yml
.env.development.local
.env.test.local
openApi/generated-dashboard/dashboard-swagger20.json
openApi/generated-onboarding/onboarding-swagger20.json
openApi/onboarding-api-docs.json
openApi/scripts/api-onboarding_fixPostGen.js
package.json
src/api/OnboardingApiClient.ts
src/utils/env.ts

Integrated OpenAPI for onboarding.
Added script to generate new client for onboarding.
Included onboarding environment variables in the DevOps configuration.
This update introduces the onboarding API to support the new "Add Administrator" flow in the Interop product. Specifically, it enables the submission of signed modules for administrator onboarding.
Tested in local enviorment.

[SELC-5371] Feat: Integrated new openApi for onboarding and generated client

---

package.json
src/components/ProductNavigationBar.tsx
src/locale/it.ts
src/pages/dashboardUserEdit/AddLegalRepresentativeForm.tsx
src/pages/dashboardUserEdit/AddProductToUserPage.tsx
src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx
src/pages/dashboardUserEdit/helpers.tsx
yarn.lock

Implemented a form for capturing the legal representative's details (name, surname, email, taxCode).
Utilized Formik for form handling and validation.
Integrated the form as a step in a multi-step wizard without changing the route.
This work is part of the flow for adding administrators via the upload of signed modules for the Interop product. The legal representative is a key role of the process, and this form facilitates their input in a structured and validated manner. 
Tested in local enviroment and by verifying with figma design.

[SELC-5369]  Feat: Add Legal Representative Form and Wizard Integration

---

src/locale/it.ts
src/pages/dashboardUserEdit/__tests__/ConfimChangeLRModal.test.tsx
src/pages/dashboardUserEdit/components/ConfimChangeLRModal.tsx

Add modal 
Add unit test
When declaring a LR thats different from the prevoius one an informative modal is required to inform the user of the change.
Tested locally and unit test

[SELC-5372] Feat: Add new modal for confirm LR change

---

src/model/UserRegistry.ts
src/pages/dashboardUserEdit/AddLegalRepresentativeForm.tsx
src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/components/MessageNoAction.tsx

Added new page for onboarding request
Added component Ending Page
In case the onboarding request is succesful show the ok Ending page that inform the user that he needs to check the mail and complete the onboarding.
Tested in local enviroment.

[SELC-5474] Feat: add success page and for onboarding request

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
openApi/generated-onboarding/onboarding-swagger20.json

updated selfcare commons library version 
updated swagger dashboard
To align the version with dashboard FE

Update selfcare commons library version and swagger

---

src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

changed function that render the role label in mobile view
The mobile view and dektop view rendered the role label differently.
Tested in local enviroment.

[SELC-5637] Feat: change render role label in mobile

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
openApi/generated-onboarding/onboarding-swagger20.json
src/api/DashboardApiClient.ts
src/model/PartyUser.ts
src/pages/dashboardUserDetail/components/UserProductAddRoles.tsx
src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx
src/services/__mocks__/usersService.ts
src/services/__tests__/usersService.test.ts
src/services/usersService.ts

Added partyRole param to saveUser api "Post"
Added partyRole param to updateUSer api "Put"
updated swagger dashboard
Updated unit tests
When adding users this two API require a new param to be passed in body "partyRole" and and not just the productRole
Tested by mocking dev eniroment data and calling the api.

[SELC-5707] Feat: add party role  to add / create users api

---

package.json
yarn.lock

update selfcare commons library

[SELC-5650] update selfcare commons library

---

src/pages/dashboardUserEdit/components/AddUserForm.tsx

Hidden add admin button for prod interop
To clean the relase for PROD
Tested locally

[SELC-5367] Hide add admin for prod interop

---

src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx

[[SELC-5367] Hide add admin for prod interop](https://github.com/pagopa/selfcare-dashboard-users-microfrontend/commit/aa742ef462de04fb74affad3746daab65e2acbb5)
To be able to deploy in PROD
Tested in dev
[SELC-5367]: https://pagopa.atlassian.net/browse/SELC-5367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5367]  hide add admin for prod release

---

package.json
src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx
yarn.lock

[SELC-5842 update selfcare commons for new action](https://github.com/pagopa/selfcare-dashboard-users-microfrontend/commit/f1859959bdc8b47787cfda2e59f67b95e7a2f0c2)
Added new action to handle users section visibility
Tested in local enviroment

[SELC-5842] Feat: update selfcare commons for new action

---

src/model/Party.tsx
src/pages/dashboardUserEdit/AddUsersPage.tsx
src/pages/dashboardUserEdit/components/AddUserForm.tsx
src/pages/dashboardUserEdit/components/MessageNoAction.tsx
src/pages/dashboardUserEdit/components/helpers.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

Add check if its an EA  adding a role or new user
Add isAggregator in onboardedProduct model
style change for outcome page
remove popup ffrom outcome page
When the Aggregator is adding a new user on prod io or prod pagopa that admin user will be  added for all the aggregates as well.
Tested locally

[SELC-5784] Feat: add logic to check if its an EA adding a new user/ role

---

src/locale/it.ts
src/microcomponents/mock_dashboard/data/party.ts
src/pages/dashboardUserEdit/components/AddUserForm.tsx

add new modal for add users in bulk
updated mock data
The aggregator can add users in bulk for all the aggregated users for prod-io and pagoPa
Tested by mocking dev enviroment

[SELC-5781] Feat:  add modal for add users in bulk

---

src/locale/it.ts
src/pages/dashboardUserEdit/EditUserRegistryPage.tsx
src/pages/dashboardUserEdit/EditUserRegistryProductPage.tsx
src/pages/dashboardUserEdit/__tests__/EditUserRegistryPage.test.tsx
src/pages/dashboardUserEdit/components/EditUserRegistryForm.tsx

update the UI of the user detail page
add new copy for the translation file.
To update the page to the new figma design.
Tested by running dashboard and users together in local enviroment

[SELC-5921] Feat: update the layout of edit user detail page

---

src/locale/de.ts
src/locale/en.ts
src/locale/fr.ts
src/locale/sl.ts

[SELC-5987] feat: Uploaded translation file provided by the agency
In order to have all the texts in the portal translated into the languages ​​provided. There may be some texts still not translated that will be collected and promptly reported to the agency.
Tested in local environment
[SELC-5987]: https://pagopa.atlassian.net/browse/SELC-5987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5987] feat: Uploaded translation file provided by the agency

---

openApi/generated-onboarding/onboarding-swagger20.json
openApi/onboarding-api-docs.json
src/pages/dashboardUserEdit/components/AddLegalRepresentativeForm.tsx

changed validation api from fetch to codegen
change checkManager api from fetch to codegen
updated swagger of onboarding
the swagger of the check manager was fixed so it can now be used to generate the client correctly and call the api.
Tested by mocking dev enviroment in local

[SELC-5959] Feat: swap validation and checkManager from fetch to codegen

---

openApi/generated-onboarding/onboarding-swagger20.json
openApi/onboarding-api-docs.json
src/locale/de.ts
src/locale/en.ts
src/locale/fr.ts
src/locale/sl.ts
src/model/ProductRole.ts
src/pages/dashboardUserEdit/components/AddLegalRepresentativeForm.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UserProductTableColumns.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

[SELC-5987] feat: Uploaded translation file provided by the agency
[SELC-5959] Feat: swap validation and checkManager from fetch to codegen
[SELC-5997] cetralized method to render the role for admin EA
Release in uat environment of the worked features
All features are tested in dev environment, for SELC-5987 is another ticket has been opened where the untranslated texts have been collected to be forwarded to the agency
[SELC-5987]: https://pagopa.atlassian.net/browse/SELC-5987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5959]: https://pagopa.atlassian.net/browse/SELC-5959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SELC-5997]: …

SELC-5987 SELC-5959 SELC-5997

---

src/locale/it.ts
src/pages/dashboardUserEdit/components/AddUserForm.tsx

changed copy for add in bulk modal
changed link copy
new copy from design.
Tested by running application locally

[SELC-5915] Feat: copy changes for  add in bulk modal and link

---

src/pages/dashboardUserEdit/components/AddLegalRepresentativeForm.tsx

[SELC-5646] feat: Added mixpanel events into add user flow
In order to monitor within the mixpanel tool, the crucial moments of the user addition flow
Tested in dev environment, the mixpanel event appear when expected
[SELC-5646]: https://pagopa.atlassian.net/browse/SELC-5646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5646] feat: Added mixpanel events into add user flow

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/api/DashboardApiClient.ts
src/api/__mocks__/DashboardApiClient.ts
src/pages/dashboardUserEdit/components/AddLegalRepresentativeForm.tsx
src/services/__mocks__/usersService.ts
src/services/__tests__/usersService.test.ts
src/services/usersService.ts

Integrate api call
update swagger
update unit tests
create mock data
api call in add Legal rappresentative page to prefill the form data
Tessted in local enviroment

[SELC-6014] Feat:  Integrate api to get the Legal rappresentative information

---

package.json
src/pages/dashboardUserEdit/components/AddLegalRepresentativeForm.tsx
yarn.lock

resolution for node fetch
remove not used dependecies
fix for check manager modal
resolutions for security vulnerabilites
Tested locally

[SELC-5934] Feat: resolution for node fetch and remov not used dependency

---

package.json
src/pages/dashboardUserDetail/__tests__/UserDetailPage.test.tsx
src/pages/dashboardUserEdit/__tests__/AddUsersPage.test.tsx
src/pages/dashboardUserEdit/__tests__/EditUserRegistryPage.test.tsx
src/pages/dashboardUsers/__tests__/UsersPage.test.tsx
src/remotes/__tests__/RoutingUsers.test.tsx
yarn.lock

[SELC-6042] feat: Updated common-frontend library dependency for introduce language detection feature
In order to introduce the language detection feature
Tested in dev environment ensuring that all the use case are satisfied
[SELC-6042]: https://pagopa.atlassian.net/browse/SELC-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6042] feat: Updated common-frontend library dependency for introduce language detection feature

---

src/locale/it.ts
src/pages/dashboardUserEdit/components/AddLegalRepresentativeForm.tsx
src/pages/dashboardUsers/UsersPage/UsersPage.tsx
src/pages/dashboardUsers/__tests__/UsersPage.test.tsx

New banner for mobile phone
redirect to edit user detail with qeury param for form field focus
fix for legal repressentative
The account team requires the admin's phone number to provide quicker and more efficient support.
Tested in local enviroment and unit test

[SELC-6090] Feat: New banner for add mobile phone number

---

openApi/dashboard-api-docs.json
openApi/generated-dashboard/dashboard-swagger20.json
src/locale/it.ts
src/model/PartyUser.ts
src/model/UserRegistry.ts
src/model/__tests__/PartyUser.test.ts
src/model/__tests__/UserRegistry.test.ts
src/pages/dashboardUserDetail/components/UserDetail.tsx
src/pages/dashboardUserDetail/userDetailPage/UserDetailPage.tsx
src/pages/dashboardUserEdit/EditUserRegistryPage.tsx
src/services/__mocks__/usersService.ts

Render the phone number in user detail page 
Render the phone number in modify user detail page
Button to add the number if its missing
update swagger
update mock data
Account need to contact the administrator through their phone number
Tested in local enviroment

[SELC-6088] Feat: Update user Detail page with phone number

---

src/pages/dashboardUserEdit/components/EditUserRegistryForm.tsx

Add mix panel event DASHBOARD_ADD_TEL
To track how many users add their number

[SELC-6092] Feat: add mixpanel event for add cell number

---

package.json
yarn.lock

hotfix: regen yarn.lock + missing dependencies

---

e2e/tests/add-and-delete-new-user.spec.ts
e2e/tests/assign-and-delete-operator-interop.spec.ts
e2e/tests/modify-user-email.spec.ts
e2e/tests/modify-user-number.spec.ts
e2e/tests/suspend-and-reactivate-user.spec.ts

extend integration tests use cases
adapt existing test
To increase the coverage on integration tests
By running the tests

[SELC-6197] Feat: extend integration tests for users

---

e2e/tests/assign-and-delete-operator-interop.spec.ts
src/locale/it.ts

Resolve main conflict

---

src/pages/dashboardUserDetail/components/UserProductActions.tsx
src/pages/dashboardUserDetail/components/UserProductRoles.tsx
src/pages/dashboardUserDetail/userDetailPage/components/UserProductDetail.tsx

removed fixed width form the chip component
removed fixed width from the product actions component
When changing to english the label would go in new line

[SELC-6307] fix: chip label style adjustment

---

e2e/playwright.config.ts
src/pages/dashboardUsers/components/UsersProductSection.tsx
src/pages/dashboardUsers/components/UsersTableProduct/components/UsersProductTable.tsx

use product role to map the user roles in the list
add slowMo for integration test and chrome browser
fix for visual bug when swithching to mobile

[SELC-6317] fix: render roles labels correctly in mobile view

---

src/locale/it.ts
src/pages/dashboardUsers/UsersPage/UsersPage.tsx
src/pages/dashboardUsers/__tests__/UsersPage.test.tsx

removed phone number
adapt unit test
THe 45 days period has passed. the banner should be removed

[SELC-6343] feat: remove phone number banner

---

package.json
src/pages/dashboardUserEdit/AddUsersPage.tsx
yarn.lock

adapted the css so that it does not get extra space based on viewport
updtaed library
on some viewports the margin between elements would increase

[SELC-6369] feat: Refine layout of 'Add Users' page and update common library

---

package.json
src/pages/dashboardUserEdit/components/AddLegalRepresentativeForm.tsx
yarn.lock

updated common version
handle status code 404 for POST /onboarding

[SELC-6417] feat: update common version to allow custom handling 404 status code

---

src/model/Party.tsx
src/model/ProductRole.ts

Add new PartyRole Admin Ea IO
updated type for partyRole

[SELC-6378] feat: handle party role Admin_EA_IO

---

src/pages/dashboardUserDetail/components/UserDetail.tsx

Hide mobile phone number .
Ui improvment so that the field is not empty.

[SELC-6502] feat: hide number when not avaible

---

package.json
src/pages/dashboardUserEdit/components/AddLegalRepresentativeForm.tsx
yarn.lock

check if response is null when sumbiting user data
update common version

fix: update common version and check for null response

---

src/utils/env.ts

update doc link for send
update doc  link fo pdnd
Switch the docs host to developer.pagopa

[SELC-6889] feat: update documentation links for SEND and PDND

---

.github/workflows/create_release_branch.yml
.github/workflows/deploy_cdn.yml

Updated ubuntu version LTS

---

src/locale/it.ts
src/pages/addUserFlow/addManager/AddLegalRepresentativeForm.tsx
src/pages/addUserFlow/addUser/AddUsersPage.tsx
src/utils/env.ts

Update roles link
Remove dynamic link for ad LR page and add fixed one to users doc

[SELC-7165] feat: Update link to documentation in add user flow

---

src/microcomponents/mock_dashboard/data/party.ts
src/pages/addUserFlow/addManager/AddLegalRepresentativeForm.tsx

get the onboarded product details based on the id selected in add user form
update the API payloads that use the institution type

[SELC-7160] feat: Enhance AddLegalRepresentativeForm to utilize actvie onboarding product details

---

.github/workflows/code_review.yaml
package.json
src/locale/it.ts
src/pages/dashboardUsers/components/MobileFilter.tsx
src/pages/dashboardUsers/components/UsersTableActions/UsersTableActions.tsx
src/pages/dashboardUsers/components/UsersTableActions/UsersTableFilters.tsx
src/pages/dashboardUsers/components/UsersTableActions/UsersTableRolesFilter.tsx
yarn.lock

update selfcare commons library with new hook
improve filters accesability
Announce when updating filters

[SELC-7418] feat: update selfcare-common-frontend to version 1.34.65 and improve accessibility features in user filters

---

src/pages/addUserFlow/addUser/components/AddUserForm.tsx

- add label for role select in AddUserForm.tsx
The input fields in the role select did not have associated labels

[SELC-7422] feat: added label for role select in AddUserForm
